apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1-debian-monasca
        env:
          - name:  FLUENT_MONASCA_KEYSTONE_URL
            value: ""
          - name:  FLUENT_MONASCA_LOG_API_URL
            value: ""
          - name:  FLUENT_USER
            value: ""
          - name:  FLUENT_PASSWORD
            value: ""
          - name:  FLUENT_DOMAIN_ID
            value: "default"
          - name:  FLUENT_MONASCA_PROJECT_NAME
            value: "magnum-cluster-1"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
